# Generated by Django 4.2.16 on 2024-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_generatervideimage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatervideimage',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=100),
        ),
    ]
